spring:
  application:
    name: Teste
  datasource:
    url: jdbc:postgresql://${URL_DB}:${PORT_DB}/${NAME_DB}  # Corrija aqui para PostgreSQL
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
    driver-class-name: "org.postgresql.Driver"
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
mockoon:
  base-url: http://localhost:3000

