version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${NAME_DB}
      POSTGRES_USER: ${USERNAME_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
    ports:
      - "${PORT_DB}:5432"
    networks:
      - spring-network

  mockoon:
    image: mockoon/cli
    volumes:
      - ./Documents/mockoon-config.json:/config/mockoon-config.json
    command: --data /config/mockoon-config.json --port 3000
    ports:
      - "3000:3000"
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge
