version: '3.8'

services:
  app:
    image: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/nome-do-repositorio:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${AWS_DB_HOST}:${AWS_DB_PORT}/${NAME_DB}
      SPRING_DATASOURCE_USERNAME: ${USERNAME_DB}
      SPRING_DATASOURCE_PASSWORD: ${PASSWORD_DB}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    logging:
      driver: awslogs
      options:
        awslogs-group: ecs-app-logs
        awslogs-region: <AWS_REGION>
        awslogs-stream-prefix: ecs

  mockoon:
    image: mockoon/cli
    volumes:
      - ./Documents/mockoon-config.json:/config/mockoon-config.json
    command: --data /config/mockoon-config.json --port 3000
    ports:
      - "3000:3000"

networks:
  default:
    driver: bridge
